export DST_SERVER_NAME="Test Dedicated Server"
export DST_CLUSTER_TOKEN="your token here"
export DST_CLUSTER_DESCRIPTION="Test description for dedicated server"
export DST_CLUSTER_INTENTION="cooperative"
export DST_CLUSTER_PASSWORD="bottleneck"